'use client';

import './globals.css';

import React from 'react';
import { Inter } from 'next/font/google';
import Theme from '../theme';
import { ThemeProvider } from '../theme/ThemeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};
interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang='en'>
      <ThemeProvider theme={Theme}>
        <body className={inter.className}>{children}</body>
      </ThemeProvider>
    </html>
  );
}
